# Generated by Django 6.0.8 on 2026-08-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_federationprofile_rewrite_lux_prefix_on_member_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
