# Generated by Django 5.2.11 on 2026-02-10 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_max_admins'),
        ('members', '0004_merge_0002_sex_0003_license_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_grade', models.CharField(blank=True, max_length=100)),
                ('to_grade', models.CharField(max_length=100)),
                ('promotion_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('proof_ref', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_history', to='clubs.club')),
                ('examiner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_grade_promotions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='members.member')),
            ],
            options={
                'ordering': ['-promotion_date', '-created_at'],
                'indexes': [models.Index(fields=['member', '-promotion_date'], name='members_gra_member__d315f4_idx'), models.Index(fields=['club', '-promotion_date'], name='members_gra_club_id_af7c3f_idx')],
            },
        ),
    ]
