# Generated by Django 5.2.11 on 2026-02-18 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0004_club_banking_and_branding_assets"),
        ("members", "0008_member_license_constraints_and_counter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="member",
            name="member_primary_secondary_role_must_differ",
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("primary_license_role", ""),
                    models.Q(
                        ("primary_license_role", models.F("secondary_license_role")),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="member_primary_secondary_role_must_differ",
            ),
        ),
    ]
