# Generated by Django 5.2.11 on 2026-02-18 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_banking_and_branding_assets'),
        ('members', '0009_remove_member_member_primary_secondary_role_must_differ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['club', 'is_active'], name='member_club_active_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['club', 'last_name', 'first_name'], name='member_club_name_idx'),
        ),
    ]
