# Generated by Django 5.2.11 on 2026-02-10 14:37

import django.db.models.deletion
import django.utils.timezone
import licenses.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_max_admins'),
        ('licenses', '0010_payment_payconiq_payment_id_and_more'),
        ('members', '0004_merge_0002_sex_0003_license_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalLicense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clubs.club')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license_type', models.ForeignKey(blank=True, db_constraint=False, default=licenses.models.get_default_license_type, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licenses.licensetype')),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member')),
            ],
            options={
                'verbose_name': 'historical license',
                'verbose_name_plural': 'historical licenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LicenseHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('issued', 'Issued'), ('renewed', 'Renewed'), ('status_changed', 'Status changed'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('payment_linked', 'Payment linked')], max_length=30)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('license_year', models.PositiveIntegerField()),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('club_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_history_events', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_history_events', to='clubs.club')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='licenses.license')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_history_events', to='members.member')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_history_events', to='licenses.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_history_events', to='licenses.payment')),
            ],
            options={
                'ordering': ['-event_at', '-id'],
                'indexes': [models.Index(fields=['member', '-event_at'], name='licenses_li_member__f1641d_idx'), models.Index(fields=['license', '-event_at'], name='licenses_li_license_e030c6_idx'), models.Index(fields=['event_type', '-event_at'], name='licenses_li_event_t_be9a80_idx')],
            },
        ),
    ]
