# Generated by Django 5.2.11 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def create_license_type_policies(apps, schema_editor):
    license_type_model = apps.get_model("licenses", "LicenseType")
    policy_model = apps.get_model("licenses", "LicenseTypePolicy")
    for license_type in license_type_model.objects.all():
        policy_model.objects.get_or_create(license_type=license_type)


def normalize_active_licenses(apps, schema_editor):
    license_model = apps.get_model("licenses", "License")
    duplicate_members = (
        license_model.objects.filter(status="active")
        .values("member_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for row in duplicate_members:
        member_id = row["member_id"]
        active_licenses = license_model.objects.filter(
            member_id=member_id, status="active"
        ).order_by("-updated_at", "-id")
        keep_license = active_licenses.first()
        if not keep_license:
            continue
        active_licenses.exclude(id=keep_license.id).update(status="pending", issued_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0011_alter_license_status_historicallicense_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseTypePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_current_year_order", models.BooleanField(default=True)),
                ("current_start_month", models.PositiveSmallIntegerField(default=1)),
                ("current_start_day", models.PositiveSmallIntegerField(default=1)),
                ("current_end_month", models.PositiveSmallIntegerField(default=12)),
                ("current_end_day", models.PositiveSmallIntegerField(default=31)),
                ("allow_next_year_preorder", models.BooleanField(default=False)),
                ("next_start_month", models.PositiveSmallIntegerField(default=12)),
                ("next_start_day", models.PositiveSmallIntegerField(default=1)),
                ("next_end_month", models.PositiveSmallIntegerField(default=12)),
                ("next_end_day", models.PositiveSmallIntegerField(default=31)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="licenses.licensetype",
                    ),
                ),
            ],
        ),
        migrations.RunPython(code=create_license_type_policies, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=normalize_active_licenses, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("member",),
                name="unique_active_license_per_member",
            ),
        ),
    ]
