# Generated by Django 5.2.11 on 2026-02-16

import django.db.models.deletion
import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0012_licensetypepolicy_unique_active_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseprice",
            name="license_type",
            field=models.ForeignKey(
                default=licenses.models.get_default_license_type,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prices",
                to="licenses.licensetype",
            ),
        ),
    ]
