# Generated by Django 5.2.11 on 2026-02-18 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_banking_and_branding_assets'),
        ('licenses', '0019_finance_performance_indexes'),
        ('members', '0009_remove_member_member_primary_secondary_role_must_differ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['member', 'year'], name='lic_member_year_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['status', 'end_date'], name='lic_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['member', 'license_type', 'year', 'status'], name='lic_m_ty_yr_st_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseprice',
            index=models.Index(fields=['license_type', '-effective_from', '-created_at'], name='licprice_type_eff_created_idx'),
        ),
    ]
