# Generated by Django 5.2.11 on 2026-02-27 20:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0023_seed_card_format_and_paper_presets'),
        ('members', '0010_member_member_club_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='artifact_pdf',
            field=models.FileField(blank=True, upload_to='print_jobs/artifacts/'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='artifact_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='printjob',
            name='artifact_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printjob',
            name='bleed_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='printjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printjob',
            name='execution_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='printjob',
            name='execution_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='printjob',
            name='include_bleed_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printjob',
            name='include_safe_area_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printjob',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printjob',
            name='safe_area_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='printjob',
            name='selected_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='printjobitem',
            constraint=models.UniqueConstraint(condition=models.Q(('slot_index__isnull', False)), fields=('print_job', 'slot_index'), name='pritem_unique_nonnull_slot_per_job'),
        ),
    ]
