# Generated by Django 5.2.11 on 2026-03-03 19:27

import django.core.validators
import django.db.models.deletion
import licenses.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_lp798_corner_radius(apps, schema_editor):
    PaperProfile = apps.get_model('licenses', 'PaperProfile')
    PaperProfile.objects.filter(code='sigel-lp798').update(card_corner_radius_mm=Decimal('3.18'))


def unseed_lp798_corner_radius(apps, schema_editor):
    PaperProfile = apps.get_model('licenses', 'PaperProfile')
    PaperProfile.objects.filter(code='sigel-lp798').update(card_corner_radius_mm=None)


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0024_printjob_artifact_pdf_printjob_artifact_sha256_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paperprofile',
            name='card_corner_radius_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='CardFontAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(max_length=500, upload_to=licenses.models.card_font_asset_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_font_assets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='cardfont_active_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(max_length=500, upload_to=licenses.models.card_image_asset_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_image_assets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='cardimg_active_name_idx')],
            },
        ),
        migrations.RunPython(seed_lp798_corner_radius, unseed_lp798_corner_radius),
    ]
