# Generated by Django 5.2.12 on 2026-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0025_paperprofile_card_corner_radius_mm_cardfontasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='side',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], default='front', max_length=10),
        ),
    ]
